### ISSUE TITLE
issue on Combine Images Into PDF

### ISSUE THREAD

**Issue by beijingjazzpanda** [Mararsh/MyBox#781] opened 2020-10-21 23:15 UTC
under combine images as pdf function, when import images (302 items, *.tif extension, total 11.5m) with thumbnail, the program show "fail".
![image](https://user-images.githubusercontent.com/10892928/96799606-17803600-1436-11eb-8d3f-e30c31680391.png)
![image](https://user-images.githubusercontent.com/10892928/96799607-1a7b2680-1436-11eb-9753-2f54cf0b05a7.png)
![image](https://user-images.githubusercontent.com/10892928/96799563-ff101b80-1435-11eb-92a6-444133006d57.png)
![image](https://user-images.githubusercontent.com/10892928/96799615-1ea74400-1436-11eb-92e4-41395937c741.png)
![image](https://user-images.githubusercontent.com/10892928/96799616-20710780-1436-11eb-951f-bb33d4bb9e49.png)

But the images can be imported without error when thumbnail is unchecked:
![image](https://user-images.githubusercontent.com/10892928/96799656-38488b80-1436-11eb-96ff-1da152cac286.png)

Another issue is when clicking "save" button to create PDF,
the program show "NullPointerException"
![image](https://user-images.githubusercontent.com/10892928/96799697-4eeee280-1436-11eb-8e63-57ce24f190ff.png)
![image](https://user-images.githubusercontent.com/10892928/96799702-51513c80-1436-11eb-8cf8-9a3679dcdb4b.png)

PDF can not be created correctly.

OS: WINDOWS 10
VERSION 6.3.4

**Comment by Mararsh** [comment] 2020-10-22 11:22
Thanks for your help!

I can recreate this issue. When files number or image pixels are too many, MyBox fails to work without detailed information.
 It looks related to memory shortage. 

Cost of cpu and memory depends on pixels number in the image instead of the image file size. Example, an image file may be small but it may includes many pixels. Image formats, like TIF and JPG, do well on compression, that means less disk and more CPU and memory.
Most algorithms will:
1) Uncompress the data in file as pixels matrix into memory.
2) Convert one color space to another. 
3) Scan the pixels matrtix as algorithms' requirements.
4) Display the pixels on interface.
5) Write data in files.
Out of memory may happen in each of above steps.

If each of images have more than 1600*2000 pixels, then 300 items means  960m pixels. Each pixel of Gray color space occupies 3 bytes, so loading all of these pixels needs 2,880m bytes. This is not enough, because  at least 5 times of memory should be ready to read, convert, display, and write the pixels.  At last, 14g memory may be asked to complete the task.(PDF generation costs much memory too.)

Possible solutions to do the task under memory pression are:
1) Make source images include less pixels.(Not reduce file size)
    Like scale them into less size, or convert images as black-white whose pixel only occupies 1 byte. 
2) Avoid conversion. Like convert JPG as PNG without alpha channel(3 bytes pixel) at first. PNG means no/less uncompression.
3) Set memory usage of PDF generation. You can do this in MyBox settings interface.
4) Enlarge limitation of JVM memory usage. By default, maximum memory for java is 1/4 of physical memory. If your computer has 16G memory, then 4G is the default value.

What MyBox can help for such issues is to improve algorithms and display useful information to user. Looks it does bad now~

Please feel free to tell your comments and suggestions. Thanks in advance!

**Comment by Mararsh** [comment] 2020-10-22 11:23
Another solution can help:
Generate some PDF files with less images, and then merge these PDF files.

**Comment by beijingjazzpanda** [comment] 2020-10-23 01:25
Thanks for your suggestion.

**Comment by Mararsh** [comment] 2020-10-23 02:50
Pixel of GRAY color space occupy 1 byte instead of 3 bytes. I made mistake. Sorry.
Updated above comments. FYI.

**Comment by Mararsh** [comment] 2020-10-24 02:13
Following can improve the preformance:
1) Lazy loading of images in table.
2) Monitor size of total pixels and show warning information when threshold reached.
3) When pixels are too many, generate smaller files and merge them as final PDF automatically. User need not know internal handling.

**Comment by Mararsh** [comment] 2020-10-24 02:15
"Null pointer" means unchecked variables and bypassed path, and should never be reached.

So this issue exposes at least 4 problems of codes. Really valuable feedback.

**Comment by beijingjazzpanda** [comment] 2020-10-24 03:57
Yes, when dealing with performance issue, it's better to think about changing algorithm.

**Comment by beijingjazzpanda** [comment] 2020-10-24 04:05
the most useful functions for me about the tools is:
split PDF into multiple images each page.
convert each image (to black/white e.g.)
creat PDF from importing multiple images.

myBox has been mentioned in 书格
https://new.shuge.org/meet/topic/1163/

I think some chinese rare book collector and relevant people may need the same functions.

**Comment by Mararsh** [comment] 2020-10-24 04:54
Thanks for the information!

Yes. Images and PDFs need be handled in many areas.
And OCR may be another useful tool for ancient books. But I could do little about this now. I hope I could do more.

**Comment by beijingjazzpanda** [comment] 2020-10-24 10:35
> Thanks for the information!
> 
> Yes. Images and PDFs need be handled in many areas.
> And OCR may be another useful tool for ancient books. But I could do little about this now. I hope I could do more.

No worry, be patient. Focus on one function until you feel satisfied. Say, image conversion. There are many tools can simply extract images from PDF and merged it back to PDF. (acrobat, e.g.) but there are rare tools which can batch process image conversion, especially the Image Binarization (I mean the quality and Fine-tuning), sometimes they have to use Photoshop to do that instead. It's suggested to do something which is highly on demand. When the tools can provide an 'one-stop' service for specific group of people, they are willing to use it for a long time. For example, It would be grateful if the tool works well to extract image from PDF, and convert images with significant algorithm with review, then merge them into PDF. This is my workflow. If I can do it effectively without any error, I would probably not use other alternatives. (In fact, the image conversion function of your tools is really useful and robust, I have never face any problem when dealing with 500+ items). Just had some error when importing images and when merging into PDF. Anyway, make it work first, and then make it right, and then make it fast. step by step.

**Comment by Mararsh** [comment] 2020-10-24 12:45
Yep. Thanks again!

**Comment by beijingjazzpanda** [comment] 2020-10-24 13:33
> Yep. Thanks again!

To improve the performance of "merging images into PDF", I have an idea :
The whole process can be divided into 3 parts;
1. import images (In this step, all processing about images from local file system into the program can be done, and save each processed images in an temporary folder)
2. convert each processed images into PDFs (instead of adding them into ONE PDF at onece, why not creating multiple single-page PDFs for each image and save them on temp folders)
3. user can review the generated PDF (at this point, the final PDF has not been generated yet, when user click "next page"/"previous page", it only switch each PDFs generated in step 2)
4. when user want to export the satisfied PDF (e.g. when they click "export"), merge all PDFs into one for them. 

The idea comes from an principle : 
There is always a trade-off between disk space and program memory. Saving all those temporary images/pdfs on the disk, can let Java garbage collect at once when it is useless. So that the Java program won't need many memories when handling large amount of items. 

I'm sorry I didn't check though your code, but I guess your program hold all items until everything is done. If so, please try to refactor it see if any improvement can be reached.

:D

**Comment by Mararsh** [comment] 2020-10-27 11:51
Thanks for you ananlysis. And sorry for replying later.
I realize images need not read in memory at all since PDF is generated by reading image files one by one. Only thumbnails should be load when user requires to show.

Current impelementation "mara.mybox.controller.ImagesListController" is a generic class for several functions, it load all images of table and ready for next maunfacture, like merging as tiff, gif, or PDF. The problem is that these objects should be done by way "write-while-reading" instead of loading all files in memory, like all batch processes.
.

**Comment by Mararsh** [comment] 2020-10-27 11:57
Currently there is a function "Compress Images in PDF" which can help to convert images in PDF as compressed ones directly, without steps like: extract images from PDF, compress them, and then write them back to PDF.
I think it can be improved as "Convert images in PDF", which can do all types of conversions.
A button "Preview" is provided in tab "target files" of some batch functions. I have not cared this button for long time and do not know whether it still works or not. I will check it later.

**Comment by Mararsh** [comment] 2020-10-27 12:13
Issue #793 is opened to solve the root reason.
It can cause all related functions work abnormally when images list is long.

**Comment by Mararsh** [comment] 2020-11-18 15:23
Fixed in v6.3.5

**Closed by Mararsh** 2020-11-18 15:23 UTC
Labels: Bug first found, Codes Optimization, Image Tools, Interface, Limitation, Performance
